# Generated by Django 4.2.7 on 2025-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Apparel'), ('food', 'Food & Beverages'), ('home', 'Home & Furniture'), ('sports', 'Sports & Outdoors'), ('beauty', 'Beauty & Health'), ('books', 'Books & Stationery'), ('automotive', 'Automotive'), ('jewelry', 'Jewelry & Accessories'), ('other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('manager', models.CharField(blank=True, max_length=100)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('color_theme', models.CharField(default='from-emerald-400 to-teal-500', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'branches',
            },
        ),
    ]
